# -*- coding: utf-8 -*-
"""Website_change_notifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PMGxUjeeEb_ins_PP-PpCBSPEzBwc8K7
"""

# Get alerted when a webpage updates (Price drops, job postings etc.,)

import requests, time

url = "https://github.com/"
last = ""

while True:
    r = requests.get(url).text
    if last and r != last:
        print("Website Updated")
    last = r
    time.sleep(60)